---
title: Fakem1ner.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  docs:
    title: docs
    output: true
theme: jekyll-theme-leap-day
